services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8181:80"
    volumes:
      - /opt/docker/vaultwarden:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8082:80"
    volumes:
      - /opt/docker/pihole/etc:/etc/pihole
      - /opt/docker/pihole/dnsmasq:/etc/dnsmasq.d
    environment:
      - TZ=Europe/Madrid
      - WEBPASSWORD=${PIHOLE_PASSWORD}
    cap_add:
      - NET_ADMIN

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3002:3000"
    volumes:
      - /opt/docker/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.hugohhm.dev
      - HOMEPAGE_VAR_NPM_USER=${HOMEPAGE_NPM_USER}
      - HOMEPAGE_VAR_NPM_PASS=${HOMEPAGE_NPM_PASS}
      - HOMEPAGE_VAR_BESZEL_USER=${HOMEPAGE_BESZEL_USER}
      - HOMEPAGE_VAR_BESZEL_PASS=${HOMEPAGE_BESZEL_PASS}
      - HOMEPAGE_VAR_GRAFANA_USER=${HOMEPAGE_GRAFANA_USER}
      - HOMEPAGE_VAR_GRAFANA_PASS=${HOMEPAGE_GRAFANA_PASS}
      - HOMEPAGE_VAR_CF_ACCOUNTID=${HOMEPAGE_CF_ACCOUNTID}
      - HOMEPAGE_VAR_CF_TUNNELID=${HOMEPAGE_CF_TUNNELID}
      - HOMEPAGE_VAR_CF_KEY=${HOMEPAGE_CF_KEY}
      - HOMEPAGE_VAR_PIHOLE_KEY=${HOMEPAGE_PIHOLE_KEY}

  ntfy:
    image: binwiederhier/ntfy:latest
    container_name: ntfy
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /opt/docker/ntfy:/var/lib/ntfy
    command:
      - serve
