name: Deploy Homelab

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Docker Compose files
        run: |
          docker compose -f docker-compose/base.yml --env-file .env config --quiet
          docker compose -f docker-compose/monitoring.yml --env-file .env config --quiet
          docker compose -f docker-compose/services.yml --env-file .env config --quiet

      - name: Deploy
        run: |
          docker compose -f docker-compose/base.yml --env-file /home/hugoh/homelab/.env up -d
          docker compose -f docker-compose/monitoring.yml --env-file /home/hugoh/homelab/.env up -d
          docker compose -f docker-compose/services.yml --env-file /home/hugoh/homelab/.env up -d

      - name: Notify success
        if: success()
        run: |
          curl -d "✔  Deploy exitoso - $(date)" https://ntfy.hugohhm.dev/hugohhm-homelab

      - name: Notify failure
        if: failure()
        run: |
          curl -d "✖  Deploy fallido - $(date)" https://ntfy.hugohhm.dev/hugohhm-homelab
