name: Sync last PR SHA

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Update last-pr-sha
        run: |
          git -C /home/hugoh/homelab fetch origin main --quiet
          SHA=$(git -C /home/hugoh/homelab rev-parse origin/main)
          echo $SHA > /home/hugoh/homelab/.last-pr-sha
          echo "Updated .last-pr-sha to $SHA"
